services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn app.main:main_app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    volumes:
      - .:/app
      - ./alembic/versions:/app/alembic/versions
    env_file:
      - .env
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python app/tg/bot.py
    depends_on:
      - app
    env_file:
      - .env


volumes:
  pg_data:
