"""created podcast_episode table

Revision ID: 605126884983
Revises: 
Create Date: 2025-06-17 11:44:33.304750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605126884983'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('podcast_episode_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('podcast_episode_id')
    )
    op.create_index(op.f('ix_episodes_podcast_episode_id'), 'episodes', ['podcast_episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_podcast_episode_id'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
